using Starter;
using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.InputSystem;

public class UiInput : MonoBehaviour
{
    StarterInput starterInput;

    public static event Action ButtonE; //change the var name

    public static event Action ButtonQ; // change the var name

    public static event Action ButtonS;
    
    public static event Action ButtonW;

    public static event Action ButtonEnter;

    public static event Action ButtonJ;

    public static event Action ButtonK;

    private void OnEnable()
    {
        starterInput = new StarterInput();

        starterInput.UI.Enable();

        starterInput.UI.Epress.performed += SlideRight;
        starterInput.UI.Qpress.performed += SLideLeft;
        starterInput.UI.Wpress.performed += SlideUp;
        starterInput.UI.Spress.performed += SlideDown;
        starterInput.UI.Enterpress.performed += PerformReturn;
        
    }

    private void OnDisable()
    {
        starterInput.UI.Epress.performed -= SlideRight;
        starterInput.UI.Qpress.performed -= SLideLeft;
        starterInput.UI.Wpress.performed -= SlideUp;
        starterInput.UI.Spress.performed -= SlideDown;
        starterInput.UI.Enterpress.performed -= PerformReturn;
    }

    private void PerformReturn(InputAction.CallbackContext obj)
    {
        ButtonEnter?.Invoke();
    }

    private void SlideDown(InputAction.CallbackContext obj)
    {
        ButtonS?.Invoke();
    }

    private void SlideUp(InputAction.CallbackContext obj)
    {
        ButtonW?.Invoke();
    }

    private void SLideLeft(InputAction.CallbackContext obj)
    {
        ButtonQ?.Invoke();
    }

    private void SlideRight(InputAction.CallbackContext obj)
    {
        ButtonE?.Invoke();
    }
}
